name: Hellow World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "hellow world"
        shell: bash
  hello-dipen:
    runs-on: ubuntu-latest
    steps:
      - name: hello dipen
        run: echo "hellow dipen"
        shell: bash
  

